markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:title
title: Rise1024.blog
url: http://Rise1024.github.io
# subscribe: http://Rise1024.github.io/feed
exclude: [ README.md, newpost.rb ]
domain: Rise1024.github.io
author: Rise1024
email: 2467220117@qq.com
safe: true
excerpt_separator: "&nbsp;"
highlight: true

theme: jekyll-theme-cayman
